create database customer_behavior;
use customer_behavior;
select * from customer;
select count(*) as rows_count from customer;
-- Customer Behavior Analysis Questions:-
-- 1.What is the total revenue generated by male vs female customers?
select gender,sum(purchased_amount) as Total_Revenue from customer
group by gender;

-- 2.Which customers used a discount but still spent more than the average purchase amount?
select * from customer;
select avg(purchased_amount) as Avg_Purchased_Amount from customer;

select customer_id,purchased_amount,discount_applied from customer
where discount_applied='Yes' and purchased_amount>=
(select avg(purchased_amount) as Avg_Purchased_amount from customer)
order by purchased_amount desc;

-- 3.Which are the top 5 products with the highest average review rating?
select top 5 item_purchased, round(avg(review_rating),2) as Avg_Review_Rating from customer
group by item_purchased
order by Avg_Review_Rating desc;

-- 4.Compare the average purchase amounts between standard and express shipping.
select shipping_type,avg(purchased_amount) as Avg_Purchase_Amounts from customer
group by shipping_type
having shipping_type in ('Standard','Express');
-- 5.Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,count(customer_id) as Total_Customers,avg(purchased_amount) as Avg_Purchased_Amount,sum(purchased_amount) as Total_Revenue from customer
group by subscription_status;
-- 6.Which 5 products have the highest percentage of purchases with discounts applied?
select top 5 item_purchased,round(100*sum(case when discount_applied='Yes' then 1 else 0 end)/count(*),2) as Discount_Rate
from customer
group by item_purchased
order by Discount_Rate desc;
-- 7.Segment customers into New, Returning and Loyal based on their total number of previous purchases and show the count of each segment.
select * from customer;
with customer_type as(
select customer_id,previous_purchases,
case
	when previous_purchases=1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
	end as customer_segment
from customer)
select customer_segment,count(*) as 'Number of Customers' from customer_type
group by customer_segment;
-- 8.What are the top 3 most purchased products within each category?
with item_counts as (
select category,item_purchased,count(customer_id) as Total_Orders,row_number() over(partition by category order by count(customer_id)desc) as Item_Rank
from customer
group by category,item_purchased)
select item_rank,item_purchased,Total_Orders from item_counts
where item_rank<=3;
-- 9.Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,count(customer_id) as repeated_buyers
from customer
where previous_purchases>5
group by subscription_status;
-- 10.What is the revenue contribution of each age group?
select age_group,sum(purchased_amount) as Revenue_Contribution from customer
group by age_group
order by Revenue_Contribution desc;